# Generated by Django 4.2.5 on 2024-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0006_rename_final_rca_validation_invalid_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='combined_shipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='deducted_at_higher_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='load_sequencing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='order_split',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='product_substitution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
